compilers:
- compiler:
    spec: intel@2021.3.0 
    paths:
      cc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icc
      cxx: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: x86_64
    modules:
    - intel/2021.3.0
    environment:
      prepend_path:
        PATH: '/apps/gnu/gcc-9.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gnu/gcc-9.2.0/lib64'
    extra_rpaths: []
