compilers:
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/intel64/icc
      cxx: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/intel64/icpc
      f77: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/intel64/ifort
      fc: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules:
    - intel/2021.3.0
    environment: {}
    extra_rpaths: []
