# TODO: Change all `/miniconda` to `/opt/miniconda` once `ufs_stack`
# issue #35 is addressed.

packages:
  all:
    compiler:: [gcc@11.4.0]
    providers:
      mpi:: [openmpi@4.0.3]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.0.3%gcc@11.4.0
  bash:
    externals:
    - spec: bash@4.2.46
      prefix: /usr
  berkeley-db:
    externals:
    - spec: berkeley-db@5.3.21
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  file:
    externals:
    - spec: file@5.11
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.5.11
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.0.2
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  git:
    externals:
    - spec: git@1.8.3.1~tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@3.82
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  hwloc:
    externals:
    - spec: hwloc@1.11.8
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@1.8.0_322-b06
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.15.1
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.3.20211021+termlib abi=6
      prefix: /miniconda
  openssh:
    externals:
    - spec: openssh@7.4p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1q
      prefix: /miniconda
  perl:
    externals:
    - spec: perl@5.16.3~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
  python:
    externals:
    - spec: python@3.9.12+bz2+ctypes+dbm+lzma+nis+pyexpat+pythoncmd+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /miniconda
  rsync:
    externals:
    - spec: rsync@3.1.2
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.38.2+fts~functions+rtree
      prefix: /miniconda
  tar:
    externals:
    - spec: tar@1.26
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.14
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.5
      prefix: /miniconda
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
