spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles

  view: false
  include: []

  specs:
  - sigio@2.3.2
  - sfcio@1.4.1
  - g2@3.4.5
  - g2tmpl@1.9.1
  - ip@4.0.0
  - nemsio@2.5.4
  - zlib@1.2.11
  - hdf5@1.10.6
  - netcdf-c@4.7.4
  - netcdf-fortran@4.5.3
  - esmf@8.4.0b08
