spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles

  view: false
  include: []

  specs:
  - cmake
  - jpeg
  - zlib
  - libpng
  - szip
  - jasper
  - udunits
  - hdf5
  - netcdf-c
  - netcdf-fortran
  - parallelio
  - nccmp
  - nco
  - cdo
  - bacio
  - sigio
  - sfcio
  - gfsio
  - w3nco
  - sp
  - ip
  - ip2
  - landsfcutil
  - nemsio
  - nemsiogfs
  - w3emc
  - g2
  - g2tmpl
  - g2c
  - crtm
  - upp
  - wrf_io
  - bufr
  - wgrib2
  - prod_util
  - grib_util
  - ncio
  - ncdiag

