spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: $env/install
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles

  view: false
  include: []

  specs:
  - sigio
  - sfcio
  - g2
  - g2tmpl
  - ip
  - nemsio
  - zlib
  - hdf5
  - netcdf-c
  - netcdf-fortran
  - esmf
